name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12', '14']
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      # Ideally yarn audit would be part of the CI flow
      # but currently there is too much noise
      # See e.g. https://github.com/facebook/create-react-app/issues/8529
      # - name: Audit dependencies
      #   - run: yarn audit

      - name: Run unit tests
        run: yarn test --coverage
        env:
          CI: true

  # Temporarily disable visual tests and run locally.
  # Backstop is not currently working with GitHub Actions.
  # visual-test:
  #   runs-on: ubuntu-latest
  #   name: Visual regression test
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Run visual regression tests
  #       run: bash ./scripts/visual-test.sh
